- name: Submit Faiss Merge Job on Hostnode
  hosts: hostnode
  become: false

  tasks:
    # create log and output directories if they don't exist
    - name: Ensure Log and Output Directories Exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /home/almalinux/nfs/logs/merge
        - /home/almalinux/nfs/faiss_index

    # count number of faiss index shards
    - name: Check Index Shard Count
      shell: "ls -1 /home/almalinux/nfs/index_shards/*.index 2>/dev/null | wc -l"
      register: shard_count

    # fail early if no faiss shards are found
    - name: Fail If No Faiss Index Shards Found
      fail:
        msg: "No faiss index shards found in /home/almalinux/nfs/index_shards"
      when: shard_count.stdout | int == 0

    # submit slurm job to merge faiss shards
    - name: Submit Faiss Merge Slurm Job
      shell: "sbatch merge_faiss_shards.slurm"
      args:
        chdir: /home/almalinux/nfs/scripts
      register: slurm_submit

    # output slurm submission result
    - name: Show Slurm Submission Result
      debug:
        msg: "Faiss merge job submitted: {{ slurm_submit.stdout }}"
