- name: BeeGFS Packages
  hosts: all
  become: true
  become_user: root
  tasks:
    # install the latest kernel headers needed for beegfs client module
    - name: Kernel Source
      ansible.builtin.dnf:
        name: "kernel-devel"
        state: latest

    # add the official beegfs yum repository for rhel9
    - name: BeeGFS Repo
      ansible.builtin.yum_repository:
        baseurl: "https://www.beegfs.io/release/beegfs_7.4.5/dists/rhel9"
        state: present
        gpgkey: "https://www.beegfs.io/release/beegfs_7.4.5/gpg/GPG-KEY-beegfs"
        gpgcheck: true
        name: "BeeGFS"
        description: "BeeGFS repo"

    # install all required beegfs components: client, storage, metadata, mgmtd, etc.
    - name: Install BeeGFS Packages
      ansible.builtin.dnf:
        name:
          - "beegfs-storage"
          - "beegfs-client"
          - "beegfs-utils"
          - "beegfs-helperd"
          - "beegfs-mgmtd"
          - "beegfs-meta"
        state: latest