- name: BeeGFS Host Configuration
  hosts: hostnode
  become: true
  become_user: root
  tasks:
    # create local temp directory to hold generated files
    - name: Create Temp Directory
      local_action: ansible.builtin.command mkdir -p ./.generated

    # generate a secure connection auth file using random bytes
    - name: Generate connauthfile
      local_action: ansible.builtin.command dd if=/dev/random of=./.generated/connauthfile bs=128 count=1

    # create directory for beegfs management daemon data
    - name: Create Management Location
      ansible.builtin.file:
        path: /beegfs_data/mgmt
        state: directory

    # run beegfs management daemon setup pointing to mgmt directory
    - name: Configure Management
      ansible.builtin.command:
        cmd: /opt/beegfs/sbin/beegfs-setup-mgmtd -p /beegfs_data/mgmt

    # create directory for beegfs metadata daemon data
    - name: Create Metadata Location
      ansible.builtin.file:
        path: /beegfs_data/md
        state: directory

    # run beegfs metadata daemon setup pointing to metadata dir and mgmt host
    - name: Configure Metadata
      ansible.builtin.command:
        cmd: /opt/beegfs/sbin/beegfs-setup-meta -p /beegfs_data/md -m hostnode

    # copy the generated connauthfile to the standard beegfs location
    - name: Auth File
      ansible.builtin.copy:
        src: ./.generated/connauthfile
        dest: /etc/beegfs/connauthfile
        owner: root
        group: root
        mode: 400

    # patch the mgmtd config to include the path to the connauthfile
    - name: Fix Management Conf
      ansible.builtin.replace:
        path: /etc/beegfs/beegfs-mgmtd.conf
        regexp: 'connAuthFile[ \t]+='
        replace: 'connAuthFile=/etc/beegfs/connauthfile'

    # patch the metadata config to include the path to the connauthfile
    - name: Fix Metadata Conf
      ansible.builtin.replace:
        path: /etc/beegfs/beegfs-meta.conf
        regexp: 'connAuthFile[ \t]+='
        replace: 'connAuthFile=/etc/beegfs/connauthfile'

    # enable and start the beegfs management daemon
    - name: Start mgmtd
      ansible.builtin.systemd_service:
        name: beegfs-mgmtd
        state: started
        enabled: true

    # enable and start the beegfs metadata daemon
    - name: Start Metadata
      ansible.builtin.systemd_service:
        name: beegfs-meta
        state: started
        enabled: true