- name: BeeGFS Common Configuration
  hosts: workers
  become: true
  become_user: root
  tasks:
    # remove any existing beegfs_data directory to start clean
    - name: Clear Old Targets
      ansible.builtin.file:
        path: /beegfs_data
        state: absent

    # create directory for the beegfs storage target
    - name: Create Target Location
      ansible.builtin.file:
        path: /beegfs_data/target
        state: directory

    # run beegfs storage setup pointing to target dir and mgmt host
    - name: Configure Storage
      ansible.builtin.command:
        cmd: /opt/beegfs/sbin/beegfs-setup-storage -p /beegfs_data/target -m hostnode

    # copy the shared connauthfile to the worker node
    - name: Auth File
      ansible.builtin.copy:
        src: ./.generated/connauthfile
        dest: /etc/beegfs/connauthfile
        owner: root
        group: root
        mode: 400

    # patch the storage config to include the path to the connauthfile
    - name: Fix Storage Conf
      ansible.builtin.replace:
        path: /etc/beegfs/beegfs-storage.conf
        regexp: 'connAuthFile[ \t]+='
        replace: 'connAuthFile=/etc/beegfs/connauthfile'

    # enable and start the beegfs storage daemon
    - name: Start Storage
      ansible.builtin.systemd_service:
        name: beegfs-storage
        state: started
        enabled: true
