- name: Download LAION Dataset to BeeGFS Storage
  hosts: hostnode, workers 
  become: true
  tasks:
    # install required python packages including clip, img2dataset, faiss, and huggingface tools
    - name: Install Required Pip Packages
      pip:
        name:
          - huggingface_hub
          - img2dataset
          - torch
          - torchvision
          - faiss-cpu
          - git+https://github.com/openai/CLIP.git
        state: present

    # export huggingface token as an environment variable for future shell access
    - name: Set Hugging Face Token as Environment Variable
      shell: |
        echo "export HF_TOKEN={{ hf_token }}" >> ~/.bashrc
        source ~/.bashrc
      environment:
        hf_token: "{{ hf_token }}"
    
    # create a shared directory on beegfs to store the laion dataset
    - name: Create Directory for LAION Data on BeeGFS
      ansible.builtin.file:
        path: "/home/almalinux/beegfs🐝/laion"
        state: directory
        mode: '0755'

    # download multiple laion parquet files from huggingface using the hf token
    - name: Download LAION Dataset Files
      ansible.builtin.shell: |
        for i in {0..9}
        do
          wget --header="Authorization: Bearer $HF_TOKEN" \
          https://huggingface.co/datasets/laion/laion2B-en-aesthetic/resolve/main/part-0000${i}-cad4a140-cebd-46fa-b874-e8968f93e32e-c000.snappy.parquet -P /beegfs🐝/laion
        done
      environment:
        HF_TOKEN: "{{ hf_token }}"
