- name: Update and Reboot All Nodes
  hosts: all
  become: true
  become_user: root

  tasks:
    # update all installed packages to their latest version
    - name: Update Packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    # reboot the system to apply any kernel or system updates
    - name: Reboot Node
      ansible.builtin.reboot: